const monsters = [
	{
		name: 'Goblin',
		size: 'small',
		race: 'humanoid',
		race_short: 'Hu',
		alignment: 'neutral evil',
		alignment_short: 'NE',
		challenge_rating: 1 / 4,
		hitpoints: 7,
		hitpoint_dice: '2d6',
		armor_class: 15,
		armor_type: 'Leather Armor, Shield',
		speed: 30,
		ability_scores: {
			strength: 8,
			dexterity: 14,
			constitution: 10,
			intelligence: 10,
			wisdom: 8,
			charisma: 8,
		},
		skills: ['stealth +6'],
		senses: ['Darkvision 60ft.', 'Passive Perception 9'],
		languages: ['Common', 'Goblin'],
		proficiency_bonus: 2,
		special_traits: [
			{
				title: 'Nimble Escape',
				description:
					'The goblin can take the Disengage or Hide action as a bonus action on each of its turns.',
			},
		],
		actions: [
			{
				weapon: 'Scimitar',
				action_type: 'melee',
				hit_modifier: 4,
				reach: 5,
				range: null,
				num_targets: 1,
				damage_average: 5,
				damage_dice: '1d6+2',
				damage_type: 'slashing',
			},
			{
				weapon: 'Shortbow',
				action_type: 'ranged',
				hit_modifier: 4,
				reach: null,
				range: '80/320 ft.',
				num_targets: 1,
				damage_average: 5,
				damage_dice: '1d6+2',
				damage_type: 'piercing',
			},
		],
	},
	{
		name: 'Hobgoblin',
		size: 'medium',
		race: 'humanoid',
		race_short: 'Hu',
		alignment: 'lawful evil',
		alignment_short: 'LE',
		challenge_rating: 1 / 2,
		hitpoints: 11,
		hitpoint_dice: '2d8+2',
		armor_class: 18,
		armor_type: 'Chain Mail, Shield',
		speed: 30,
		ability_scores: {
			strength: 13,
			dexterity: 12,
			constitution: 12,
			intelligence: 10,
			wisdom: 10,
			charisma: 9,
		},
		skills: null,
		senses: ['Darkvision 60ft.', 'Passive Perception 10'],
		languages: ['Common', 'Goblin'],
		proficiency_bonus: 2,
		special_traits: [
			{
				title: 'Martial Advantage',
				description:
					"Once per turn, the hobgoblin can deal an extra 7 (2d6) damage to a creature it hits with a weapon attack if that creature is within 5 feet of an ally of the hobgoblin that isn't incapacitated.",
			},
		],
		actions: [
			{
				weapon: 'Longsword',
				action_type: 'melee',
				hit_modifier: 3,
				reach: 5,
				range: null,
				num_targets: 1,
				damage_average: 5,
				damage_dice: '1d8+1',
				damage_type: 'slashing',
			},
			{
				weapon: 'Longbow',
				action_type: 'ranged',
				hit_modifier: 3,
				reach: null,
				range: '150/600 ft.',
				num_targets: 1,
				damage_average: 5,
				damage_dice: '1d8+1',
				damage_type: 'piercing',
			},
		],
	},
];

export default monsters;
