const monsters = [
    {
        name: "Goblin",
        size: "small",
        race: "humanoid",
        race_short: "Hu",
        alignment: "neutral evil",
        alignment_short: "NE",
        challenge_rating: 1 / 4,
        hitpoints: 7,
        hitpoint_dice: "2d6",
        armor_class: 15,
        armor_type: "Leather Armor, Shield",
        speed: 30,
        ability_scores: {
            strength: 8,
            dexterity: 14,
            constitution: 10,
            intelligence: 10,
            wisdom: 8,
            charisma: 8,
        },
        skills: ["stealth +6"],
        senses: ["Darkvision 60ft.", "Passive Perception 9"],
        languages: ["Common", "Goblin"],
        proficiency_bonus: 2,
        special_traits: [
            {
                title: "Nimble Escape",
                description:
                    "The goblin can take the Disengage or Hide action as a bonus action on each of its turns.",
            },
        ],
        actions: [
            {
                weapon: "Scimitar",
                action_type: "melee",
                hit_modifier: 4,
                reach: 5,
                range: null,
                num_targets: 1,
                damage_average: 5,
                damage_dice_text: "1d6+2",
                damage_die: 6,
                damage_die_num: 1,
                damage_modifier: 2,
                damage_type: "slashing",
            },
            {
                weapon: "Shortbow",
                action_type: "ranged",
                hit_modifier: 4,
                reach: null,
                range: "80/320 ft.",
                num_targets: 1,
                damage_average: 5,
                damage_dice_text: "1d6+2",
                damage_die: 6,
                damage_die_num: 1,
                damage_modifier: 2,
                damage_type: "piercing",
            },
        ],
    },
    {
        name: "Hobgoblin",
        size: "medium",
        race: "humanoid",
        race_short: "Hu",
        alignment: "lawful evil",
        alignment_short: "LE",
        challenge_rating: 1 / 2,
        hitpoints: 11,
        hitpoint_dice: "2d8+2",
        armor_class: 18,
        armor_type: "Chain Mail, Shield",
        speed: 30,
        ability_scores: {
            strength: 13,
            dexterity: 12,
            constitution: 12,
            intelligence: 10,
            wisdom: 10,
            charisma: 9,
        },
        skills: null,
        senses: ["Darkvision 60ft.", "Passive Perception 10"],
        languages: ["Common", "Goblin"],
        proficiency_bonus: 2,
        special_traits: [
            {
                title: "Martial Advantage",
                description:
                    "Once per turn, the hobgoblin can deal an extra 7 (2d6) damage to a creature it hits with a weapon attack if that creature is within 5 feet of an ally of the hobgoblin that isn't incapacitated.",
            },
        ],
        actions: [
            {
                weapon: "Longsword",
                action_type: "melee",
                hit_modifier: 3,
                reach: 5,
                range: null,
                num_targets: 1,
                damage_average: 5,
                damage_dice_text: "1d8+1",
                damage_die: 8,
                damage_die_num: 1,
                damage_modifier: 1,
                damage_type: "slashing",
            },
            {
                weapon: "Longbow",
                action_type: "ranged",
                hit_modifier: 3,
                reach: null,
                range: "150/600 ft.",
                num_targets: 1,
                damage_average: 5,
                damage_dice_text: "1d8+1",
                damage_die: 8,
                damage_die_num: 1,
                damage_modifier: 1,
                damage_type: "piercing",
            },
        ],
    },
    {
        name: "Ogre",
        size: "large",
        race: "giant",
        race_short: "Gi",
        alignment: "chaotic evil",
        alignment_short: "CE",
        challenge_rating: 2,
        hitpoints: 59,
        hitpoint_dice: "7d10+21",
        armor_class: 11,
        armor_type: "Hide Armor",
        speed: 40,
        ability_scores: {
            strength: 19,
            dexterity: 8,
            constitution: 16,
            intelligence: 5,
            wisdom: 7,
            charisma: 7,
        },
        skills: null,
        senses: ["Darkvision 60ft.", "Passive Perception 8"],
        languages: ["Common", "Giant"],
        proficiency_bonus: 2,
        special_traits: null,
        actions: [
            {
                weapon: "Greatclub",
                action_type: "melee",
                hit_modifier: 6,
                reach: 5,
                range: null,
                num_targets: 1,
                damage_average: 13,
                damage_dice_text: "2d8+4",
                damage_die: 8,
                damage_die_num: 2,
                damage_modifier: 4,
                damage_type: "bludgeoning",
            },
            {
                weapon: "Javelin",
                action_type: "melee/ranged",
                hit_modifier: 6,
                reach: 5,
                range: "30/120 ft.",
                num_targets: 1,
                damage_average: 11,
                damage_dice_text: "2d6+4",
                damage_die: 6,
                damage_die_num: 2,
                damage_modifier: 4,
                damage_type: "piercing",
            },
        ],
    },
];

export default monsters;
